Add homepage
MesakDuduCoder/Module-One-Capstone-Mesak pull request #1
Opened 2023-03-24 18:18 UTC by MesakDuduCoder

This is my Capstone project for module one, it is an online learning website. It has cool animation effects and a stylish and modern design. I hope that you like it and take something away from my work.

2023-03-24 19:55 UTC, m05e5 requested changes
Hi @MesakDuduCoder , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)



## Highlights

✔️ Very nice UI
✔️ No linters error
✔️ Professional readme file

## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Please check the comments below 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 19:55 UTC, m05e5 commented on about.html
> +                <div class="orange-line-2 mb-3 mt-1"></div>
- [ ] Hey. You are required to follow HTML semantics. So, kindly make sure you have only one `h1` tag per page

2023-03-24 19:55 UTC, m05e5 commented on about.html
> +                </div>
- [ ] Please as part of the requirements you are supposed to follow the design as much as possible. Kindly make sure that for this section, the images are transparent with an orange background color and some text on it as it is on the design

**Design**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/37901469/227621465-5a7f080b-8945-41a7-af7a-73a93fc17e0f.png">

**Your app**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/37901469/227621537-e50ea56b-2f4d-4544-b9ea-971e1a6767b7.png">

2023-03-24 19:55 UTC, m05e5 commented on index.html
> +    </section>
- [ ] You are required to follow HTML semantics. So, kindly make sure you have at least one `h1` tag per page

2023-03-24 19:55 UTC, m05e5 commented on index.html
> +            </div>
- [ ] For accessibility purpose and to make sure you follow HTML semantics please make sure you have a significant alternative text for each image.

2023-03-24 19:55 UTC, m05e5 commented on about.html
> +        </div>
- [ ] You are required to follow HTML semantics. Kindly make sure every page has a `footer` tag

2023-03-25 15:01 UTC, MesakDuduCoder commented
Can you please request further changes as optional because I'm running out of time and I don't have any block repeat left.

2023-03-25 15:09 UTC, ABDULALI3468 approved these changes
Hi @MesakDuduCoder , 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 15:17 UTC, merged